version: '3.8'

services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    restart: unless-stopped

  python-app:
    build: ./python-app
    ports:
      - "5000:5000"
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped
